// <auto-generated />
using EnfermariaSenac.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnfermariaSenac.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20231112120508_Usuarios")]
    partial class Usuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("EnfermariaSenac.Models.Enfermagem", b =>
                {
                    b.Property<int>("ID_Enfermagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coren")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome_Enfermagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID_Enfermagem");

                    b.ToTable("Enfermagem");
                });

            modelBuilder.Entity("EnfermariaSenac.Models.Paciente", b =>
                {
                    b.Property<int>("ID_Paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alergico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data_Nasc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome_Paciente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID_Paciente");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("EnfermariaSenac.Models.Prontuario", b =>
                {
                    b.Property<int>("ID_Prontuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ID_Enfermagem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ID_Paciente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome_Enfermagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome_Paciente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relatorioatendimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID_Prontuario");

                    b.ToTable("Prontuario");
                });
#pragma warning restore 612, 618
        }
    }
}
